import { chromium } from 'playwright';
const [out] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
page.setDefaultTimeout(300000);
page.on('pageerror', e => console.log('pageerror', e.message));
await page.goto('http://localhost:4173/?view=univers');
await page.waitForSelector('.experience.is-loaded', { timeout: 300000 });
await page.waitForTimeout(3000);
await page.screenshot({ path: out + '/u1.png' });
await page.evaluate(() => window.dispatchEvent(new CustomEvent('pf-seek', { detail: 0.086 })));
await page.waitForTimeout(4000);
await page.screenshot({ path: out + '/u2.png' });
await page.evaluate(() => document.querySelector('.menu-trigger').click());
await page.waitForTimeout(2000);
await page.screenshot({ path: out + '/u3.png' });
const audit = await page.evaluate(() => [...document.querySelectorAll('dialog[open] a, dialog[open] button, .site-header a, .site-header button, .tour-hud button')].filter(e => e.getClientRects().length).map(e => { const b = e.getBoundingClientRect(); return b.height < 40 ? (e.textContent.trim().slice(0, 20) + ' ' + Math.round(b.height)) : null; }).filter(Boolean));
console.log('small targets', JSON.stringify(audit), 'scrollW', await page.evaluate(() => document.documentElement.scrollWidth));
await browser.close();
